name: Test (Run Tests)

on:
  pull request:
     branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        user: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "22.x"

      - name: Setup dependencies
        run: npm install

      - name: Run tests
        run: npm test
